### ISSUE TITLE
build_all_themes.sh create nothing

### ISSUE THREAD

**Issue by P6g9YHK6** [kir4h/docker-hackmyresume-all-themes#2]
i have run build_all_themes.sh and the script is running smoothly as the logs shows.
but i am have got no html nor pdf created in the folder.

i have tired playing with the permissions on the folder inside and outside the container no luck.

**Comment by kir4h** [comment]
Long time since I haven't used it, I will give it a try and let you know.

Could you please paste a log of your steps (commands + output) to reproduce them?

**Comment by P6g9YHK6** [comment]
/ # build_all_themes.sh

*** HackMyResume v1.9.0-beta ***
Reading JRS resume: /resumes/resume.json
Applying JSONRESUME-THEME-BOOTSTRAP-ICONS theme (5 formats)

*** HackMyResume v1.9.0-beta ***
Reading JRS resume: /resumes/resume.json
Applying JSONRESUME-THEME-CLASS theme (5 formats)

*** HackMyResume v1.9.0-beta ***
Reading JRS resume: /resumes/resume.json
Applying JSONRESUME-THEME-CLASSY theme (5 formats)

*** HackMyResume v1.9.0-beta ***
Reading JRS resume: /resumes/resume.json
Applying JSONRESUME-THEME-COMPACT theme (5 formats)

*** HackMyResume v1.9.0-beta ***
Reading JRS resume: /resumes/resume.json
Applying JSONRESUME-THEME-COMPACT-EXTENDED theme (5 formats)

*** HackMyResume v1.9.0-beta ***
Reading JRS resume: /resumes/resume.json
Applying JSONRESUME-THEME-CONTEMPO theme (5 formats)

*** HackMyResume v1.9.0-beta ***
Reading JRS resume: /resumes/resume.json
Applying JSONRESUME-THEME-DARK-CLASSY theme (5 formats)

*** HackMyResume v1.9.0-beta ***
Reading JRS resume: /resumes/resume.json
Applying JSONRESUME-THEME-DARK-CLASSY-RESPONSIVE theme (5 formats)

*** HackMyResume v1.9.0-beta ***
Reading JRS resume: /resumes/resume.json
Applying JSONRESUME-THEME-ELEGANT theme (5 formats)

*** HackMyResume v1.9.0-beta ***
Reading JRS resume: /resumes/resume.json
Applying JSONRESUME-THEME-ELEGANT-FR theme (5 formats)

*** HackMyResume v1.9.0-beta ***
Reading JRS resume: /resumes/resume.json
Applying JSONRESUME-THEME-ELOQUENT theme (5 formats)

*** HackMyResume v1.9.0-beta ***
Reading JRS resume: /resumes/resume.json
Applying JSONRESUME-THEME-KENDALL theme (5 formats)

*** HackMyResume v1.9.0-beta ***
Reading JRS resume: /resumes/resume.json
Applying JSONRESUME-THEME-KENDALL-BEARDTREE theme (5 formats)

*** HackMyResume v1.9.0-beta ***
Reading JRS resume: /resumes/resume.json
Applying JSONRESUME-THEME-MODERN theme (5 formats)

*** HackMyResume v1.9.0-beta ***
Reading JRS resume: /resumes/resume.json
Applying JSONRESUME-THEME-MODERN-EXTENDED theme (5 formats)

*** HackMyResume v1.9.0-beta ***
Reading JRS resume: /resumes/resume.json
Applying JSONRESUME-THEME-NAMEME theme (5 formats)

*** HackMyResume v1.9.0-beta ***
Reading JRS resume: /resumes/resume.json
Applying JSONRESUME-THEME-ONEPAGE theme (5 formats)

*** HackMyResume v1.9.0-beta ***
Reading JRS resume: /resumes/resume.json
Applying JSONRESUME-THEME-SCEPTILE theme (5 formats)

*** HackMyResume v1.9.0-beta ***
Reading JRS resume: /resumes/resume.json
Applying JSONRESUME-THEME-SHORT theme (5 formats)

*** HackMyResume v1.9.0-beta ***
Reading JRS resume: /resumes/resume.json
Applying JSONRESUME-THEME-SLICK theme (5 formats)

*** HackMyResume v1.9.0-beta ***
Reading JRS resume: /resumes/resume.json
Applying JSONRESUME-THEME-SPARTAN theme (5 formats)

*** HackMyResume v1.9.0-beta ***
Reading JRS resume: /resumes/resume.json
Applying JSONRESUME-THEME-STACKOVERFLOW theme (5 formats)

*** HackMyResume v1.9.0-beta ***
Reading JRS resume: /resumes/resume.json
Applying JSONRESUME-THEME-STACKOVERFLOW2 theme (5 formats)

*** HackMyResume v1.9.0-beta ***
Reading JRS resume: /resumes/resume.json
Applying JSONRESUME-THEME-STRIKING theme (5 formats)
/ #

**Comment by P6g9YHK6** [comment]
i have tried a few combinaison of file name/arguments but i am suspecting that maybe my .json is not read properly for some reason but it works fine with any of the original project themes.

**Comment by kir4h** [comment]
Are you running it using the docker image? And if so, are you bind mounting the folder?

Just tested it, in my case there is a line showing that PDF resume is being generated

```shell
$ docker run --rm --name=hackmyresume -it -v $(pwd)/tmp:/resumes kir4h/hackmyresume-all-themes build_all_themes.sh kir4h

*** HackMyResume v1.9.0-beta ***
Reading JRS resume: /resumes/resume.json
Applying JSONRESUME-THEME-BOOTSTRAP-ICONS theme (5 formats)
Generating PDF  resume: resumes/kir4h-bootstrap-icons.pdf

*** HackMyResume v1.9.0-beta ***
Reading JRS resume: /resumes/resume.json
Applying JSONRESUME-THEME-CLASS theme (5 formats)
Generating PDF  resume: resumes/kir4h-class.pdf

.....
```

Checking tmp folder contains the files

```shell
ls tmp/
kir4h-bootstrap-icons.pdf       kir4h-classy.pdf.html            kir4h-contempo.pdf          kir4h-elegant-fr.pdf.html  kir4h-kendall-beardtree.pdf       kir4h-modern-extended.pdf.html  kir4h-onepage.pdf        kir4h-short.pdf.html    kir4h-stackoverflow2.pdf       kir4h-striking.pdf.html
kir4h-bootstrap-icons.pdf.html  kir4h-compact-extended.pdf       kir4h-contempo.pdf.html     kir4h-elegant.pdf          kir4h-kendall-beardtree.pdf.html  kir4h-modern.pdf                kir4h-onepage.pdf.html   kir4h-slick.pdf         kir4h-stackoverflow2.pdf.html  resume.json
kir4h-class.pdf                 kir4h-compact-extended.pdf.html  kir4h-dark-classy.pdf       kir4h-elegant.pdf.html     kir4h-kendall.pdf                 kir4h-modern.pdf.html           kir4h-sceptile.pdf       kir4h-slick.pdf.html    kir4h-stackoverflow.pdf
kir4h-class.pdf.html            kir4h-compact.pdf                kir4h-dark-classy.pdf.html  kir4h-eloquent.pdf         kir4h-kendall.pdf.html            kir4h-nameme.pdf                kir4h-sceptile.pdf.html  kir4h-spartan.pdf       kir4h-stackoverflow.pdf.html
kir4h-classy.pdf                kir4h-compact.pdf.html           kir4h-elegant-fr.pdf        kir4h-eloquent.pdf.html    kir4h-modern-extended.pdf         kir4h-nameme.pdf.html           kir4h-short.pdf          kir4h-spartan.pdf.html  kir4h-striking.pdf
```

**Comment by P6g9YHK6** [comment]
Yes i am using the image and yes the folder is bind mounted i have plenty of bind mounted container that work without any issue.

but yes indeed a line is missing from the log. what could make this happen ?

**Comment by P6g9YHK6** [comment]
i have tired running the following with the same results

/ # hackmyresume build /resumes/resume.json

*** HackMyResume v1.9.0-beta ***
Reading JRS resume: /resumes/resume.json
Converting /resumes/resume.json to FRESH format.
Applying MODERN theme (8 formats)

have you got another .json that i could try with ? i would like to eliminate this as the cause of the issue.

**Comment by kir4h** [comment]
I'm thinking it might be something related to the .json as you mentioned? You mentioned that it worked fine with any of the original project themes, but not sure if you are using the same version for testing that.

In any case, could you please provide me an anonymized version of your resume.json to play with?

EDIT: just read your comment, will also look for a resume.json that works so that you can try it to narrow the issue down

**Comment by kir4h** [comment]
Tested it with the one used for  tests and working https://raw.githubusercontent.com/hacksalot/HackMyResume/master/test/expected/modern/resume.json . Could you please try it?

**Comment by P6g9YHK6** [comment]
Indeed it works.

my .json works perfectly with these themes https://jsonresume.org/themes/ i am narrowing down what part of it is the issue.

PS:   "projects": [ ] is not on the official schema is there somewhere some documentation about it ?

**Comment by P6g9YHK6** [comment]
Found it !  it was an "endDate": "2016-14-01",
with the month and the day inverted ><
The other themes didn't cared but here it just broke everything
Anyhow thanks for the help :)

**Comment by kir4h** [comment]
> PS: "projects": [ ] is not on the official schema is there somewhere some documentation about it ?

https://github.com/jsonresume/resume-schema/blob/master/schema.json#L412

Kind of confusing since https://jsonresume.org/schema/ hasn't been updated. I remember noticing this when building the image.

> Found it ! it was an "endDate": "2016-14-01",
> with the month and the day inverted ><
> The other themes didn't cared but here it just broke everything
> Anyhow thanks for the help :)

Glad you found the issue! It would be nice to get some warning log about it, but it seems it's failing silently :(
